name: 'Pull Request Action ðŸš€'

on: 
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ðŸ”ƒ Install
        run: |
          yarn
      - name: ðŸ§± Build
        run: |
          yarn build
      - uses: ./
        with:
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_TEXT: 'thanks for submitting a pull request! We will try to review it as soon as we can :)'  #enter your custom comment in the content variable
          PR_REACTION: 'rocket' #enter your reaction here
          GIPHY_TOPIC: 'Thanks a lot' #enter your topic here
          TAG_AUTHOR: true #enter true if you want to tag the author of the pull request or enter fase
          ASSIGN_TO_AUTHOR: true #enter true if you want to assign the pull request to the author or enter false
